### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by publicarray** [ibksturm/dnscrypt-switzerland#1]
Good work!
Keep in mind that dnscrypt-proxy clients will, by default only check for a new certificate [every 4 hours](https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-proxy/example-dnscrypt-proxy.toml#L126)
but is shorter (10 sec) [when there are no servers available](https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-proxy/proxy.go#L164-L169)

https://github.com/ibksturm/dnscrypt-switzerland/blob/b5c58913e81bc6a8d3656ffe629e1b57b9318b3d/cron.daily/unbound-key#L6-L9

So I would assume in the worst case the client won't use your server for 4 hours when the cert expires.

I'm not entirely sure so please test first.

**Comment by ibksturm** [comment]
hi sebastian, thanks for your input

good point of you, i‘ve got this problem with my personal test in the range of one day (25...30 hours) , so thats the reason i wrote the daily script... perhabts its better to move it on the cron.hourly folder

i‘ll look this sunday on it (saturday i have to go with my wife to depeche mode )

**Comment by publicarray** [comment]
Moving the cron job to hourly would not fix it. Instead it will likely not work for longer periods of time. It is better to serve 2 sets of key and certificate pairs and rotate between them. The second certificate is for clients that can use the old cert during the 4 hour window. Here is an example with dnscrypt-wrapper: https://github.com/cofyc/dnscrypt-wrapper#key-rotation for unbound the `dnscrypt-provider-cert-rotated` is probably the option to use to serve the old cert with. (It is also possible to use more than 2 sets of key and certificate pairs. For example to generate a cert that is used in the future)

**Comment by ibksturm** [comment]
hi sebastian

thanks to your input, i‘ll look on sunday to optimised my code

greets

**Comment by ibksturm** [comment]
hi sebastian

update, i scripted some new files

a) a cron.hourly job to generate 2.cert and 2.key
b) updateing unbound.conf.d/dnscrypt.conf with 2 lines to handle the second cert and key (thanks for your tip!)

i think it should be better

**Comment by publicarray** [comment]
Why are you recreating the key/cert pair every hour?

**Comment by ibksturm** [comment]
simple reason, kids are dtarted party in their bed (better than sleeping) and i needed a quick and dirty solution to bring the server back...

but soon is sunday and i could think deeper about cert exchange
